# Generated by Django 5.2.5 on 2025-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
